language: python
python:
  # - "2.6"
  - "2.7"

before_install:
  - pip install -r requirements.txt
  - invoke build

install:
  - pip install dist/autolycus-*.whl

before_script:
  - invoke clean
  - rm -rf autolycus/ setup.py # eliminate any way to import the source

script:
  - invoke test
