sudo: false
language: python
python:
  # - "2.6"
  - "2.7"

env:
  - INSTALL_WHEEL=0
  - INSTALL_WHEEL=1

before_install:
  - pip install -r requirements.txt
  - invoke build

install:
  - invoke install

before_script:
  - invoke clean
  - rm -rf autolycus/ setup.py # eliminate any way to import the source

script:
  - invoke test --coverage

after_success:
  - codecov
